### ISSUE TITLE
es6-shim.min.js (v0.34.1) in SharePoint - Uncaught Sys.ParameterCountException: Sys.ParameterCountException: Parameter count mismatch.

### ISSUE THREAD

**Issue by williamyinssw** [paulmillr/es6-shim#399] opened 2016-01-12 06:02 UTC
When 'es6-shim.min.js' is referred in any SharePoint 2013 page, 

<pre>&lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.0/es6-shim.min.js&quot;&gt;&lt;/script&gt;</pre>

it shows the following error:

<pre>Uncaught Sys.ParameterCountException: Sys.ParameterCountException: Parameter count mismatch.  ScriptResource.axd?d=....
</pre>

This may be a conflict issue with .NET Ajax controls..

**Comment by ljharb** [comment] 2016-01-12 08:53
Can you provide a reproducible test case, ideally on a jsfiddle?

Does that error come with any sort of stack trace? What happens if you include the non-minified version?

**Comment by arntj** [comment] 2016-02-05 10:43
All it takes to reproduce this issue, is to include the MicrosoftAjax 3.5 js (debug version) **before** ES6 shims. I've reproduced it in Chrome in the following jsfiddle (remember to have the browser debug console open before running it):

https://jsfiddle.net/p8ysoxts/

(Note: This fiddle is apparently empty, because there is no code needed to reproduce this issue, all you have to do is to include the js files.)

**Comment by arntj** [comment] 2016-02-05 10:50
I've also reproduced it with Microsoft Ajax 4.5.2:

https://jsfiddle.net/18pdk5u3/

**Comment by arntj** [comment] 2016-02-05 11:50
The problem is that Microsoft Ajax enforces validation of parameters on String.prototype.startsWith, so that it throws an exception when it is called with more than one parameter. ES6 runs this function with two parameters as a part of a feature check (line 830 in es6-shim.js). This could be fixed by wrapping this line in a try-catch.

**Comment by ljharb** [comment] 2016-02-05 19:05
In general, shims and polyfills need to always be run first, before application code (and language shims should run before engine-level shims). If you include es5-shim and es6-shim before your Ajax lib, does everything work?

**Comment by arntj** [comment] 2016-02-08 11:49
Yes, it does work, but it's a little inconvenient given the current architecure of our website.

**Comment by ljharb** [comment] 2016-02-08 20:08
I'll fix this one - my general policy is *not* to fix errors like this, unless it's easy - and in this case it's easy.

Thanks for confirming!

**Comment by ljharb** [comment] 2016-02-09 18:01
This fix will be included in the next release. However, I'd recommend updating this Ajax library that's doing the wrong thing with startsWith, as well as loading the es5-shim and es6-shim first, before anything else.

**Closed** 2016-02-09 18:01 UTC
